version: '3.6'
services:
  redis-master:
    build:
      context: ./redis
    container_name: redis-master
    ports:
      - '6380:6379'
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redisdb-m:/data/db
    networks:
      - redis-cluster

  redis-slave1:
    container_name: redis-slave1
    image: redis:7
    command:  redis-server --slaveof redis-master 6379 --masterauth qwerty  --requirepass qwerty
    depends_on:
      - redis-master
    volumes:
      - redisdb-s1:/data/db
    networks:
      - redis-cluster

volumes:
  redisdb-m: {}
  redisdb-s1: {}

networks:
  redis-cluster:
    driver: bridge
